services:
  nperf: 
    container_name: speedtest
    image: debian:speedtest
    build: 
      context: .
      dockerfile: Dockerfile_Debian_Bookworm
    cpus: 8
    mem_limit: 8gb
    restart: always
  