FROM debian:bookworm

# Crear el archivo debian.sources con los repositorios necesarios
RUN sed -i 's/Components: main/Components: main contrib non-free non-free-firmware/' /etc/apt/sources.list.d/debian.sources

# DNS
COPY ./my_resolv.conf /etc/resolv.conf
#RUN echo nameserevr=1.1.1.1 > /etc/resolv.conf 
RUN cat /etc/resolv.conf 


# Actualizar la lista de paquetes
RUN apt update && apt upgrade -y && apt install -y wget

# Herramientas dignostico de red
RUN apt install -y iputils-ping \
    bind9-dnsutils \
    netcat-openbsd \
    iproute2 \
    traceroute \
    inetutils-tools \
    procps

# Herramientas adicionales
RUN apt install -y tmux htop ccze

# Paquetes para fuse
RUN apt install -y squashfuse fuse3
RUN groupadd fuse

# Instalacion de speedtest cli para hacer pruebas (temporal)
RUN apt install -y curl && \
    curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh | bash && \
    apt install -y speedtest

ARG USERNAME=ooklauser
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN groupadd -f --gid $USER_GID $USERNAME && \
    useradd --uid $USER_UID --gid $USER_GID -mG users,fuse $USERNAME

# Concede permisos FUSE dentro del contenedor
RUN echo "$USERNAME:$USERNAME" >> /etc/fuse_lowuser

USER $USERNAME
WORKDIR /home/$USERNAME
RUN wget https://install.speedtest.net/ooklaserver/ooklaserver.sh
RUN chmod +x ooklaserver.sh

# Ejecuta la instalación con -f (¡Ahora sí funciona directamente!)
RUN ./ooklaserver.sh -f install

RUN echo "Proceso de configuración" && \
echo "OoklaServer.useIPv6 = true " >>  OoklaServer.properties && \
echo "OoklaServer.allowedDomains = *.ookla.com, *.speedtest.net" >>  OoklaServer.properties && \
echo "OoklaServer.enableAutoUpdate = true" >>  OoklaServer.properties &&\
echo "OoklaServer.ssl.useLetsEncrypt = true" >>  OoklaServer.properties

#EXPOSE 8080 
#EXPOSE 5060

RUN ./ooklaserver.sh start