services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ooklaserver-server
    # Use this on servers where actual free memory is low
    # to prevent the container from being killed by oom_killer
    # It is usually fine to have this on when --memory is present,
    # since --memory is the maximum amount that the container
    # can allocate. This container usually runs with one
    # OoklaServer process, therefore oom_kill_disable: true
    # is safe to use here.
    oom_kill_disable: true
    # 2G for 1Gbps, 8G for 10 or more Gbps, more memory = more simultaneous
    # clients. All of these should be the same value in order to stop
    # memory from being swapped out or having other processes/containers
    # being allowed to use the range that the container can allocate from.
    # Avoiding that contentions reduces latency and allows OoklaServer to
    # deliver the most accurate results.
    mem_limit: 2g
    memswap_limit: 2g
    mem_reservation: 2g
    # the directory the compose file is in should also
    # have the OoklaServer binary and an OoklaServer.properties file,
    # it will be mounted as /server within the container:
    volumes:
      - .:/opt
    # if someones stopping the container, give a few seconds towards
    # sending out final tcp finacks, but otherwise yank the rug out
    # fairly quick so that the next instance can be started wihout
    # waiting the default 10s:
    stop_grace_period: 3s
    restart: "unless-stopped"
    entrypoint:
      - "/server/OoklaServer="
      - "-d"
    # Docker's health check is "informational" unless using Docker Swarm.
    # The healthcheck can be scripted by checking the JSON output from the
    # command "docker inspect OoklaServer" on the docker host.
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080 || exit 1
      interval: 5s
      timeout: 5s
      retries: 2
    networks:
      speedtest:
        ipv4_address: 190.103.31.10
        ipv6_address: 2803:c000:13e:1::12

networks:
  speedtest:
    external: true